# Generated by Django 4.1.2 on 2022-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'Atlanta Hawks'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Boston Celtics', 'Boston Celtics'), ('Charlotte Hornets', 'Charlotte Hornets')], default='Atlanta Hawks', max_length=20),
        ),
    ]
