# Generated by Django 4.1.2 on 2022-10-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'Atlanta Hawks'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Boston Celtics', 'Boston Celtics'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Chicago Bulls', 'Chicago Bulls'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Denver Nuggets', 'Denver Nuggets'), ('Detroit Pistons', 'Detroit Pistons'), ('Golden State Warriors', 'Golden State Warriors'), ('Houston Rockets', 'Houston Rockets'), ('Indiana Pacers', 'Indiana Pacers'), ('Los Angeles Clippers', 'Los Angeles Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Miami Heat', 'Miami Heat'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('Minnesota Timberwolves', 'Minnesota Timberwolves'), ('National Basketball Association', 'National Basketball Association'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('New York Knicks', 'New York Knicks'), ('Oklahoma City Thunders', 'Oklahoma City Thunders'), ('Orlando Magic', 'Orlando Magic'), ('Philadelphia 76ers', 'Philadelphia 76ers'), ('Phoenix Suns', 'Phoenix Suns'), ('Portland Trailblazers', 'Portland Trailblazers'), ('Sacramento Kings', 'Sacramento Kings'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Toronto Raptors', 'Toronto Raptors'), ('Utah Jazz', 'Utah Jazz'), ('Washington Wizards', 'Washington Wizards')], default='National Basketball Association', max_length=31),
        ),
    ]
