# Generated by Django 4.1.3 on 2022-11-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_right_handed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='profiles/'),
        ),
    ]
