# Generated by Django 4.1.3 on 2022-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'ATL'), ('Brooklyn Nets', 'BKN'), ('Boston Celtics', 'BOS'), ('Charlotte Hornets', 'CHA'), ('Chicago Bulls', 'CHI'), ('Cleveland Cavaliers', 'CLE'), ('Dallas Mavericks', 'DAL'), ('Denver Nuggets', 'DEN'), ('Detroit Pistons', 'DET'), ('Golden State Warriors', 'GSW'), ('Houston Rockets', 'HOU'), ('Indiana Pacers', 'IND'), ('Los Angeles Clippers', 'LAC'), ('Los Angeles Lakers', 'LAL'), ('Memphis Grizzlies', 'MEM'), ('Miami Heat', 'MIA'), ('Milwaukee Bucks', 'MIL'), ('Minnesota Timberwolves', 'MIN'), ('National Basketball Association', 'NBA'), ('New Orleans Pelicans', 'NOP'), ('New York Knicks', 'NYK'), ('Oklahoma City Thunders', 'OKC'), ('Orlando Magic', 'ORL'), ('Philadelphia 76ers', 'PHI'), ('Phoenix Suns', 'PHX'), ('Portland Trailblazers', 'POR'), ('Sacramento Kings', 'SAC'), ('San Antonio Spurs', 'SAS'), ('Toronto Raptors', 'TOR'), ('Utah Jazz', 'UTA'), ('Washington Wizards', 'WAS')], default='National Basketball Association', max_length=31),
        ),
    ]
