# Generated by Django 4.1.3 on 2022-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_team',
            field=models.CharField(choices=[('ATL', 'ATL'), ('BKN', 'BKN'), ('BOS', 'BOS'), ('CHA', 'CHA'), ('CHI', 'CHI'), ('CLE', 'CLE'), ('DAL', 'DAL'), ('DEN', 'DEN'), ('DET', 'DET'), ('GSW', 'GSW'), ('HOU', 'HOU'), ('IND', 'IND'), ('LAC', 'LAC'), ('LAL', 'LAL'), ('MEM', 'MEM'), ('MIA', 'MIA'), ('MIL', 'MIL'), ('MIN', 'MIN'), ('NBA', 'NBA'), ('NOP', 'NOP'), ('NYK', 'NYK'), ('OKC', 'OKC'), ('ORL', 'ORL'), ('PHI', 'PHI'), ('PHX', 'PHX'), ('POR', 'POR'), ('SAC', 'SAC'), ('SAS', 'SAS'), ('TOR', 'TOR'), ('UTA', 'UTA'), ('WAS', 'WAS')], default='NBA', max_length=31),
        ),
    ]
