# Generated by Django 4.1.3 on 2022-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_favorite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct_guesses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='incorrect_guesses',
            field=models.IntegerField(null=True),
        ),
    ]
