# Generated by Django 4.1.2 on 2022-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='winning_team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
