# Generated by Django 4.1.2 on 2022-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_winning_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='away_team_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='home_team_score',
            field=models.IntegerField(null=True),
        ),
    ]
