# Generated by Django 4.1.2 on 2022-11-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_away_team_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
