# Generated by Django 4.1.2 on 2022-11-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_away_team_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='away_team',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='home_team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
