# Generated by Django 4.1.2 on 2022-11-02 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0007_alter_card_away_team_alter_card_home_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=255, null=True)),
                ('away_team', models.CharField(max_length=255, null=True)),
                ('home_team_score', models.IntegerField(default=0, null=True)),
                ('away_team_score', models.IntegerField(default=0, null=True)),
                ('user_pick', models.CharField(max_length=255)),
                ('winning_team', models.CharField(max_length=255, null=True)),
                ('user_pick_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('user_pick', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
