# Generated by Django 4.1.3 on 2022-11-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_game_created_at_remove_game_user_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_pick_correct',
        ),
    ]
