# Generated by Django 4.1.3 on 2022-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_remove_game_user_remove_game_user_pick_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick_correct',
            field=models.BooleanField(default=False),
        ),
    ]
