# Generated by Django 4.1.3 on 2022-11-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_pick_pick_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='pick_correct',
        ),
    ]
