# Generated by Django 4.1.3 on 2022-11-10 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0013_remove_pick_pick_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
