# Generated by Django 4.1.3 on 2022-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
