# Generated by Django 4.1.3 on 2022-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_challenge_delete_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='opponent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
